version: 2
updates:
  - package-ecosystem: npm
    directory: /
    schedule:
      interval: weekly
    groups:
      npm:
        patterns: ["*"]
        update-types: [minor, patch]
    ignore:
      - dependency-name: "@datafuel/*"
      - dependency-name: "@clack/prompts"
        update-types: ["version-update:semver-major"]
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
    groups:
      actions:
        patterns: ["*"]
